### ISSUE TITLE
生长系统

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [PlantTreeFirstThenGetRich/androidapp-TREE#2]

**Comment by CSshengxy** [comment]
1. 程序下载时间决定生长状况（种子、树苗、小树、大树）

2. 程序下载时间决定浇水情况（配合天气接口）

3.程序下载时间决定落叶掉落和消失数量

**Comment by CSshengxy** [comment]
以上三点已经完成。
@BecksIsAlreadyTaken @CuttlefishXuan @wenhuigit
