### ISSUE TITLE
运行环境搭建

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [PlantTreeFirstThenGetRich/androidapp-TREE#3]

**Comment by CSshengxy** [comment]
![image](https://user-images.githubusercontent.com/33179899/40150788-6a7a7658-59ae-11e8-8c28-4a8d6f4654f3.png)

**Comment by CuttlefishXuan** [comment]
![image](https://user-images.githubusercontent.com/30437016/40268966-0ba1b008-5baa-11e8-9318-2b9ac2a83b7a.png)
还没学怎么用，先来打个卡~di

**Comment by BecksIsAlreadyTaken** [comment]
![image](https://user-images.githubusercontent.com/20657361/40304250-832277d2-5d28-11e8-801e-2f954c667320.png)


其实我上周就安好了

**Comment by wenhuigit** [comment]
![image](https://user-images.githubusercontent.com/30816940/40361505-23fe0d8c-5dfc-11e8-8a50-c2c06cc24876.png)
